version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    hostname: "intranet.blegal.cloud"
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      SMTP_SERVER: smtplocal
    depends_on:
      - db
      - smtp
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "intranet.blegal.cloud"
      traefik.enable: "true"
      traefik.domain: "intranet.blegal.cloud"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host(`intranet.blegal.cloud`);Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host(`intranet.blegal.cloud`)
      traefik.longpolling-0.frontend.rule: Host(`intranet.blegal.cloud`);Path:/websocket,/websocket/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.alt-1.frontend.redirect.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.alt-1.frontend.redirect.replacement: $$1://intranet.blegal.cloud/$$3
      traefik.alt-1.frontend.rule: Host(`blegal.tecnativa.net`)
      traefik.http.middlewares.blegal-odoo-17-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.blegal-odoo-17-0-prod-compress.compress: "true"
      traefik.http.middlewares.blegal-odoo-17-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag:
        "noindex, nofollow"
      traefik.http.middlewares.blegal-odoo-17-0-prod-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.blegal-odoo-17-0-prod-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.blegal-odoo-17-0-prod-forceSecure.redirectScheme.permanent: "true"
      traefik.http.services.blegal-odoo-17-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.blegal-odoo-17-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.blegal-odoo-17-0-prod-main-0.rule: Host(`intranet.blegal.cloud`)
      traefik.http.routers.blegal-odoo-17-0-prod-main-0.service: blegal-odoo-17-0-prod-main
      traefik.http.routers.blegal-odoo-17-0-prod-main-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-buffering,
        blegal-odoo-17-0-prod-compress, blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-main-secure-0.rule: Host(`intranet.blegal.cloud`)
      traefik.http.routers.blegal-odoo-17-0-prod-main-secure-0.service: blegal-odoo-17-0-prod-main
      traefik.http.routers.blegal-odoo-17-0-prod-main-secure-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-buffering,
        blegal-odoo-17-0-prod-compress, blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-0.rule:
        Host(`intranet.blegal.cloud`) && Path(`/websocket`)
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-0.service: blegal-odoo-17-0-prod-longpolling
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-secure-0.rule:
        Host(`intranet.blegal.cloud`) && Path(`/websocket`)
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-secure-0.service: blegal-odoo-17-0-prod-longpolling
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-secure-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-0.rule:
        Host(`intranet.blegal.cloud`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-0.service: blegal-odoo-17-0-prod-main
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-buffering,
        blegal-odoo-17-0-prod-compress, blegal-odoo-17-0-prod-forbid-crawlers,
        blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`intranet.blegal.cloud`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-secure-0.service: blegal-odoo-17-0-prod-main
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-secure-0.middlewares:
        blegal-odoo-17-0-prod-addSTS, blegal-odoo-17-0-prod-buffering,
        blegal-odoo-17-0-prod-compress, blegal-odoo-17-0-prod-forbid-crawlers,
        blegal-odoo-17-0-prod-forceSecure
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt
      traefik.http.middlewares.blegal-odoo-17-0-prod-redirect-1.redirectRegex.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.http.middlewares.blegal-odoo-17-0-prod-redirect-1.redirectRegex.replacement: $$1://intranet.blegal.cloud/$$3
      traefik.http.routers.blegal-odoo-17-0-prod-redirect-1.rule: Host(`blegal.tecnativa.net`)
      traefik.http.routers.blegal-odoo-17-0-prod-redirect-1.service: blegal-odoo-17-0-prod-main
      traefik.http.routers.blegal-odoo-17-0-prod-redirect-1.middlewares:
        blegal-odoo-17-0-prod-compress, blegal-odoo-17-0-prod-redirect-1

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

  smtp:
    extends:
      file: common.yaml
      service: smtpreal
    env_file:
      - .docker/smtp.env
    networks:
      default:
        aliases:
          - smtplocal
    restart: unless-stopped

  backup:
    extends:
      file: common.yaml
      service: backup
    env_file:
      - .docker/backup.env
      - .docker/db-access.env
    restart: unless-stopped
    depends_on:
      - db
      - smtp

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  backup_cache:
  filestore:
  db:
  mailconfig:
  maildata:
  maillogs:
  maillogssupervisord:
  mailstate:
