version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-test}"
      # To install demo data export DOODBA_WITHOUT_DEMO=false
      WITHOUT_DEMO: "${DOODBA_WITHOUT_DEMO-all}"
      SMTP_PORT: "1025"
      SMTP_SERVER: smtplocal
    restart: unless-stopped
    hostname: "intranet-test.blegal.cloud"
    depends_on:
      - db
      - remote_blegal_mssql_proxy
      - smtp
    networks:
      default:
      globalwhitelist_shared:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "intranet-test.blegal.cloud"
      traefik.enable: "true"
      traefik.domain: "intranet-test.blegal.cloud"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host:intranet-test.blegal.cloud;Path:/{anything:.*}
      traefik.longpolling-0.frontend.rule: Host:intranet-test.blegal.cloud;Path:/websocket,/websocket/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.alt-1.frontend.redirect.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.alt-1.frontend.redirect.replacement: $$1://intranet-test.blegal.cloud/$$3
      traefik.alt-1.frontend.rule: Host:demo-blegal.tecnativa.net
      traefik.http.services.blegal-odoo-17-0-test-main.loadbalancer.server.port: 8069
      traefik.http.services.blegal-odoo-17-0-test-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-0.rule:
        Host(`intranet-test.blegal.cloud`) && Path(`/websocket`)
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-0.service: blegal-odoo-17-0-test-longpolling
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-forceSecure
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-secure-0.rule:
        Host(`intranet-test.blegal.cloud`) && Path(`/websocket`)
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-secure-0.service: blegal-odoo-17-0-test-longpolling
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-secure-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-forceSecure
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-test-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-0.rule:
        Host(`intranet-test.blegal.cloud`) && (PathPrefix(`/`))
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-0.service: blegal-odoo-17-0-test-main
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-buffering,
        blegal-odoo-17-0-test-compress, blegal-odoo-17-0-test-forbid-crawlers,
        blegal-odoo-17-0-test-forceSecure
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-secure-0.rule:
        Host(`intranet-test.blegal.cloud`) && (PathPrefix(`/`))
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-secure-0.service: blegal-odoo-17-0-test-main
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-secure-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-buffering,
        blegal-odoo-17-0-test-compress, blegal-odoo-17-0-test-forbid-crawlers,
        blegal-odoo-17-0-test-forceSecure
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-test-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt
      traefik.http.middlewares.blegal-odoo-17-0-test-redirect-1.redirectRegex.regex: ^(.*)://([^/]+)/(.*)$$
      traefik.http.middlewares.blegal-odoo-17-0-test-redirect-1.redirectRegex.replacement: $$1://intranet-test.blegal.cloud/$$3
      traefik.http.routers.blegal-odoo-17-0-test-redirect-1.rule: Host(`demo-blegal.tecnativa.net`)
      traefik.http.routers.blegal-odoo-17-0-test-redirect-1.service: blegal-odoo-17-0-test-main
      traefik.http.routers.blegal-odoo-17-0-test-redirect-1.middlewares:
        blegal-odoo-17-0-test-compress, blegal-odoo-17-0-test-redirect-1
    command:
      - odoo
      - --workers=2
      - --max-cron-threads=1

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped

  smtp:
    extends:
      file: common.yaml
      service: smtpfake
    restart: unless-stopped
    networks:
      default:
        aliases:
          - smtplocal
      inverseproxy_shared:
    labels:
      doodba.domain.main: "intranet-test.blegal.cloud"
      traefik.docker.network: "inverseproxy_shared"
      traefik.enable: "true"
      traefik.frontend.passHostHeader: "true"
      traefik.mailhog-0.frontend.rule: Host:intranet-test.blegal.cloud;PathPrefixStrip:/smtpfake/
      traefik.mailhog-0.port: 8025
      # Mailhog service
      traefik.http.middlewares.blegal-odoo-17-0-test-mailhog-stripprefix.stripPrefix.prefixes: /smtpfake/
      traefik.http.services.blegal-odoo-17-0-test-mailhog.loadbalancer.server.port: 8025
      traefik.http.middlewares.blegal-odoo-17-0-test-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.blegal-odoo-17-0-test-compress.compress: "true"
      traefik.http.middlewares.blegal-odoo-17-0-test-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag:
        "noindex, nofollow"
      traefik.http.middlewares.blegal-odoo-17-0-test-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.blegal-odoo-17-0-test-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.blegal-odoo-17-0-test-forceSecure.redirectScheme.permanent: "true"
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-0.rule:
        Host(`intranet-test.blegal.cloud`) && PathPrefix(`/smtpfake/`)
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-0.service: blegal-odoo-17-0-test-mailhog
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-buffering,
        blegal-odoo-17-0-test-compress, blegal-odoo-17-0-test-forbid-crawlers,
        blegal-odoo-17-0-test-forceSecure, blegal-odoo-17-0-test-mailhog-stripprefix
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-secure-0.rule:
        Host(`intranet-test.blegal.cloud`) && PathPrefix(`/smtpfake/`)
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-secure-0.service: blegal-odoo-17-0-test-mailhog
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-secure-0.middlewares:
        blegal-odoo-17-0-test-addSTS, blegal-odoo-17-0-test-buffering,
        blegal-odoo-17-0-test-compress, blegal-odoo-17-0-test-forbid-crawlers,
        blegal-odoo-17-0-test-forceSecure, blegal-odoo-17-0-test-mailhog-stripprefix
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-secure-0.tls: "true"
      traefik.http.routers.blegal-odoo-17-0-test-mailhog-secure-0.tls.certResolver: letsencrypt
    volumes:
      - "smtpconf:/etc/mailhog:ro,z"
    entrypoint: [sh, -c]
    command:
      - test -r /etc/mailhog/auth && export MH_AUTH_FILE=/etc/mailhog/auth; exec MailHog

  remote_blegal_mssql_proxy:
    image: tecnativa/whitelist
    restart: unless-stopped
    networks:
      default:
        aliases:
          - blegaldb.tecnativa.net
      public:
    environment:
      TARGET: blegaldb.tecnativa.net
      PORT: "1449 1449"
      PRE_RESOLVE: 1

networks:
  default:
    internal: ${DOODBA_NETWORK_INTERNAL-true}
    driver_opts:
      encrypted: 1

  public:

  globalwhitelist_shared:
    external: true

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
  smtpconf:
