[options]
# These are Tecnativa's defaults, based on real cases.
# They are optimized for shared servers with big capacity.
# See https://www.tecnativa.com/r/oxK for more details.

# Kill workers that use more than 32 GiB
limit_memory_hard = 34359740000

# Recycle workers after finishing a process if they reach 6 GiB
limit_memory_soft = 6442451000

# Recycle workers after finishing this amount of requests
limit_request = 50000

# Our users are very patient and can wait for 24 hours for any process
limit_time_real = 86400

# Any known valid cron should finish before 2 hours
limit_time_real_cron = 72000

# 12 hours of CPU time in the real execution time configured above
# is a CPU leak for sure
limit_time_cpu = 43200

# If a cron gets stuck, at least there should be another one to process
# incoming mails, a critical cron job in Odoo deployments
max_cron_threads = 2

# This should handle fine 48 concurrent users
workers = 8
