# Copyright 2024 Tecnativa - Víctor Martínez
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
import datetime

from .common import TestBaseImportPdfByTemplateBase


class TestBaseImportPdfByTemplateBgbl(TestBaseImportPdfByTemplateBase):
    def test_account_invoice_bgbl_alhambral(self):
        self._set_template_values("account_move_alhambra")
        attachment = self._create_ir_attachment("bgbl/account-move-alhambra.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "FR2410461")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 16))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 25.87)

    def test_account_invoice_bgbl_amazon(self):
        self._set_template_values("account_move_amazon")
        attachment = self._create_ir_attachment("bgbl/account-move-amazon.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "ES42NJQEAEUI")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 18))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 50.64)

    def test_account_invoice_bgbl_aquaservice(self):
        self._set_template_values("account_move_aquaservice")
        attachment = self._create_ir_attachment("bgbl/account-move-aquaservice.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "241115367972")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 18))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 62.75)

    def test_account_invoice_bgbl_bnp(self):
        self._set_template_values("account_move_bnp")
        attachment = self._create_ir_attachment("bgbl/account-move-bnp.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "FJF56585")
        self.assertEqual(record.invoice_date, datetime.date(2024, 11, 5))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 191.22)

    def test_account_invoice_bgbl_catasus(self):
        self._set_template_values("account_move_catasus")
        attachment = self._create_ir_attachment("bgbl/account-move-catasus.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "A 24003041")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 107.44)

    def test_account_invoice_bgbl_cronuts(self):
        self._set_template_values("account_move_cronuts")
        attachment = self._create_ir_attachment("bgbl/account-move-cronuts.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "F241634")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 20))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 702.02)

    def test_account_invoice_bgbl_google_ads(self):
        self._set_template_values("account_move_google_ads")
        attachment = self._create_ir_attachment("bgbl/account-move-google_ads.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "5083267358")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 30))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertAlmostEqual(record.invoice_line_ids.price_unit, 425.59)

    def test_account_invoice_bgbl_hetzner(self):
        self._set_template_values("account_move_hetzner")
        attachment = self._create_ir_attachment("bgbl/account-move-hetzner.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "088000046903")
        self.assertEqual(record.invoice_date, datetime.date(2024, 11, 10))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 10.90)

    def test_account_invoice_bgbl_hgm(self):
        self._set_template_values("account_move_hgm")
        attachment = self._create_ir_attachment("bgbl/account-move-hgm.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "232791")
        self.assertEqual(record.invoice_date, datetime.date(2024, 12, 2))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 14)

    def test_account_invoice_bgbl_julia_fargas(self):
        self._set_template_values("account_move_julia_fargas")
        attachment = self._create_ir_attachment("bgbl/account-move-julia_fargas.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "22")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 30))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 1806.65)

    def test_account_invoice_bgbl_limpiezas_noemi(self):
        self._set_template_values("account_move_limpiezas_noemi")
        attachment = self._create_ir_attachment("bgbl/account-move-limpiezas_noemi.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "241549")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 30))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 310)

    def test_account_invoice_bgbl_mariana_campos(self):
        self._set_template_values("account_move_mariana_campos")
        attachment = self._create_ir_attachment("bgbl/account-move-mariana_campos.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "2025")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 29))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 2450)

    def test_account_invoice_bgbl_metodo_consolida(self):
        self._set_template_values("account_move_metodo_consolida")
        attachment = self._create_ir_attachment(
            "bgbl/account-move-metodo_consolida.pdf"
        )
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "F240182")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 2))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 236.25)

    def test_account_invoice_bgbl_ninite(self):
        self._set_template_values("account_move_ninite")
        attachment = self._create_ir_attachment("bgbl/account-move-ninite.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "2UNEWFSP")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 29))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 10)

    def test_account_invoice_bgbl_opcion_energia(self):
        self._set_template_values("account_move_opcion_energia")
        attachment = self._create_ir_attachment("bgbl/account-move-opcion_energia.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "FE24019695")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 31))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 101.09)

    def test_account_invoice_bgbl_revive_forestal(self):
        self._set_template_values("account_move_revive_forestal")
        attachment = self._create_ir_attachment("bgbl/account-move-revive_forestal.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "6")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 8))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 766.66)

    def test_account_invoice_bgbl_tecnologia_familiar(self):
        self._set_template_values("account_move_tecnologia_familiar")
        attachment = self._create_ir_attachment(
            "bgbl/account-move-tecnologia_familiar.pdf"
        )
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "SAJ/2024/4526")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 4))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 360.68)

    def test_account_invoice_bgbl_tuxis(self):
        self._set_template_values("account_move_tuxis")
        attachment = self._create_ir_attachment("bgbl/account-move-tuxis.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "F21991")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 18)
