# Copyright 2024 Tecnativa - Víctor Martínez
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
import datetime

from .common import TestBaseImportPdfByTemplateBase


class TestBaseImportPdfByTemplateAcm(TestBaseImportPdfByTemplateBase):
    def test_account_invoice_acm_bgbl(self):
        self._set_template_values("account_move_bgbl")
        attachment = self._create_ir_attachment("acm/account-move-bgbl.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "1/12")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 30))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 79170.21)

    def test_account_invoice_acm_claris(self):
        self._set_template_values("account_move_claris")
        attachment = self._create_ir_attachment("acm/account-move-claris.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "1/22")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 2))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 2796.64)

    def test_account_invoice_acm_control(self):
        self._set_template_values("account_move_control")
        attachment = self._create_ir_attachment("acm/account-move-control.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "7/\n4893")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 29))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 24.92)

    def test_account_invoice_acm_gesprat(self):
        self._set_template_values("account_move_gesprat")
        attachment = self._create_ir_attachment("acm/account-move-gesprat.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "1/11")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 2))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 626.97)

    def test_account_invoice_acm_innov_despacho(self):
        self._set_template_values("account_move_innov_despacho")
        attachment = self._create_ir_attachment("acm/account-move-innov_despacho.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "13889")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 20))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 426.67)

    def test_account_invoice_acm_manuel_robles(self):
        self._set_template_values("account_move_manuel_robles")
        attachment = self._create_ir_attachment("acm/account-move-manuel_robles.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "202501")
        self.assertEqual(record.invoice_date, datetime.date(2025, 1, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertAlmostEqual(record.invoice_line_ids.price_unit, 813.42)

    def test_account_invoice_acm_quipu(self):
        self._set_template_values("account_move_quipu")
        attachment = self._create_ir_attachment("acm/account-move-quipu.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "2024E-2992")
        self.assertEqual(record.invoice_date, datetime.date(2024, 9, 30))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 711)

    def test_account_invoice_acm_santiago_alonso(self):
        self._set_template_values("account_move_santiago_alonso")
        attachment = self._create_ir_attachment("acm/account-move-santiago_alonso.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "000144")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 31))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 1097.4)

    def test_account_invoice_acm_siemens(self):
        self._set_template_values("account_move_siemens")
        attachment = self._create_ir_attachment("acm/account-move-siemens.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "53140104909170")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 4))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 50.53)
