# Copyright 2024 Tecnativa - Víctor Martínez
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
import datetime

from .common import TestBaseImportPdfByTemplateBase


class TestBaseImportPdfByTemplateBlegal(TestBaseImportPdfByTemplateBase):
    def test_account_invoice_blegal_araceli(self):
        self._set_template_values("account_move_araceli")
        attachment = self._create_ir_attachment("blegal/account-move-araceli.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "32/2024 ")
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 1781.29)

    def test_account_invoice_blegal_axesor(self):
        self._set_template_values("account_move_axesor")
        attachment = self._create_ir_attachment("blegal/account-move-axesor.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "24044670-I")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 6.5)

    def test_account_invoice_blegal_col_graduados(self):
        self._set_template_values("account_move_col_graduados")
        attachment = self._create_ir_attachment("blegal/account-move-col_graduados.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "202411422")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 128.44)

    def test_account_invoice_blegal_col_registradores(self):
        self._set_template_values("account_move_col_registradores")
        attachment = self._create_ir_attachment(
            "blegal/account-move-col_registradores.pdf"
        )
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "2024/278331")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 31))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 2.6)

    def test_account_invoice_blegal_cooltra(self):
        self._set_template_values("account_move_cooltra")
        attachment = self._create_ir_attachment("blegal/account-move-cooltra.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "FS1-1148505")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 2))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 156)

    def test_account_invoice_blegal_deh(self):
        self._set_template_values("account_move_deh")
        attachment = self._create_ir_attachment("blegal/account-move-deh.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "AS/01449413")
        self.assertEqual(record.invoice_date, datetime.date(2024, 10, 7))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 820)

    def test_account_invoice_blegal_equifax(self):
        self._set_template_values("account_move_equifax")
        attachment = self._create_ir_attachment("blegal/account-move-equifax.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "5010FR10108638")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 6))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 44.11)

    def test_account_invoice_blegal_format(self):
        self._set_template_values("account_move_format")
        attachment = self._create_ir_attachment("blegal/account-move-format.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "GARAJE MONZA PK19- LYNK CO.")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 5))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 145)

    def test_account_invoice_blegal_logalty(self):
        self._set_template_values("account_move_logalty")
        attachment = self._create_ir_attachment("blegal/account-move-logalty.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "20240409557")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 22))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 166.13)

    def test_account_invoice_blegal_marta(self):
        self._set_template_values("account_move_marta")
        attachment = self._create_ir_attachment("blegal/account-move-marta.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "45/24")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 31))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertAlmostEqual(record.invoice_line_ids.price_unit, 3116.22)

    def test_account_invoice_blegal_movistar(self):
        self._set_template_values("account_move_movistar")
        attachment = self._create_ir_attachment("blegal/account-move-movistar.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "FMPVAHH0015633")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 25))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 91.24)

    def test_account_invoice_blegal_rcr(self):
        self._set_template_values("account_move_rcr")
        attachment = self._create_ir_attachment("blegal/account-move-rcr.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "PO20623/24")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 42)

    def test_account_invoice_blegal_silcar(self):
        self._set_template_values("account_move_silcar")
        attachment = self._create_ir_attachment("blegal/account-move-silcar.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "A  111498")
        self.assertEqual(record.invoice_date, datetime.date(2024, 7, 31))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertAlmostEqual(record.invoice_line_ids.price_unit, 72.96)

    def test_account_invoice_blegal_stripe(self):
        self._set_template_values("account_move_stripe")
        attachment = self._create_ir_attachment("blegal/account-move-stripe.pdf")
        wizard = self._create_wizard_base_import_pdf_upload(attachment)
        res = wizard.action_process()
        self.assertEqual(res["res_model"], "account.move")
        record = self.env[res["res_model"]].browse(res["res_id"])
        self.assertIn(attachment, record.attachment_ids)
        self.assertEqual(record.move_type, "in_invoice")
        self.assertEqual(record.ref, "CSMJX9ZU-2024-07")
        self.assertEqual(record.invoice_date, datetime.date(2024, 8, 1))
        self.assertEqual(record.partner_id, self.partner)
        self.assertEqual(len(record.invoice_line_ids), 1)
        self.assertEqual(record.invoice_line_ids.product_id, self.product)
        self.assertEqual(record.invoice_line_ids.quantity, 1)
        self.assertEqual(record.invoice_line_ids.price_unit, 5.17)
