{
    "name": "Blegal - Custom",
    "version": "17.0.1.0.0",
    "summary": "Custom Blegal",
    "sequence": 10,
    "author": "Tecnativa",
    "category": "Accounting/Accounting",
    "website": "https://www.tecnativa.com",
    "depends": [
        "account",
        "account_payment_term_extension",
        "base_import_pdf_by_template_account",
    ],
    "data": [
        "data/account_payment_data.xml",
        "data/base_import_pdf_template_data.xml",
        # "data/product_attribute_data.xml",
        # "report/report_deliveryslip.xml",
        # "report/report_purchaseorder.xml",
        # "report/report_sale_order.xml",
        "views/account_move_views.xml",
        "views/res_partner_views.xml",
    ],
    "license": "AGPL-3",
}
